### ISSUE TITLE
Add repository owner environment variable in release process

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12840]
Whenever I am testing changes in the release process, I often have to make such changes to point to my local fork.

https://github.com/stoyanK7/checkstyle/commit/2600b41317e42d2b6a283ac53b3c35009fcf5401
![Screenshot from 2023-03-14 18-49-36](https://user-images.githubusercontent.com/23459549/225093862-1cefa452-8cc7-449f-a0b5-b11454214b6b.png)

---
We can use the [`github.repository_owner` variable](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) and set it as an env variable for example. This will ease troubleshooting/testing those workflows in the future if they break.
```yml
      - name: Run Shell Script
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          ./.ci/some-release-script.sh
```

```sh
checkForVariable "REPOSITORY_OWNER"
...
-X GET https://api.github.com/repos/$REPOSITORY_OWNER/checkstyle/milestones?state=open \
```

I should have done this proposal long ago to be honest..
