### ISSUE TITLE
Mobile page rendering requires extra font difference for properties 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13195]
Detected at https://github.com/checkstyle/checkstyle/pull/13103#issuecomment-1585814118

There only pop point to improve is to make name of property to be italic to look different than description.

![Screenshot_20230610-135311](https://github.com/checkstyle/checkstyle/assets/812984/1589d89e-6fbf-45a9-ac8f-5971f6c69af0)

**Comment by stoyanK7** [comment]
@romani Is this what we are looking for?
![Screenshot from 2023-06-12 19-52-05](https://github.com/checkstyle/checkstyle/assets/23459549/895fc74d-eaef-4260-9784-9d1e0768fb27)
```css
section[id$="_Properties"] .wrapper .bodyTable tr td:first-child {
  font-style: italic;
}
```
