### ISSUE TITLE
Move fast tasks from CircleCI to Cirrus

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#14878]
**Reason**: Cirrus CI builds are useless now. They are only run for master and all tasks are duplicated by appveyor build.
On the other hand, CircleCI has too many builds + it has restrictions for developers (e.g. I am not allowed to run builds there)

So, workload can be balanced a bit with some jobs moved to Cirrus. 
There is a [limitation from Cirrus](https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/) that does not allow us to run some long-running tasks for each PR. However, there are some very fast tasks, that look like a good candidates to be moved to Cirrus.
Those are:
```
  git-validation:
    jobs:
      - validate-with-script:
          name: "git-no-merge-commits"
          command: "./.ci/validation.sh git-no-merge-commits"
      - validate-with-script:
          name: "git-check-pull-number"
          command: "./.ci/validation.sh git-check-pull-number"
```
they together take about 1 minute, so it should be more than enough to run them on every PR and respect the limit.
![изображение](https://github.com/checkstyle/checkstyle/assets/8901354/a309c89a-4407-4ee0-9dbc-6cf4e3c54e86)

There are also other good candidates for transfer, such as
![изображение](https://github.com/checkstyle/checkstyle/assets/8901354/70051ee2-1e3c-4548-9ef8-777f5695f5fd)

but they can be moved later

https://github.com/checkstyle/checkstyle/blob/0a341c4dc53b149ee42c5ddf8e5507d44738c6eb/.cirrus.yml#L3
