### ISSUE TITLE
Remove condition for triggering new workflow on active PR

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15400]
Remove below as it doesn't seem to work

```
on:
  pull_request:
    types:
      - opened
```
