### ISSUE TITLE
Investigate step `Setup local maven cache` in regression-report.yml

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15634]
```
      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
```

We investigate where wer are storing or restoring the cache and understand more on it to optimise further. 

Use `uses: actions/cache/restore@v4` to define exact function of action - `restore`
