### ISSUE TITLE
Investigate reducing extra cache on step `Restore Generated Config and Project Files` in regression-report.yml

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15635]
```
      - name: Restore Generated Config and Project Files
        if: needs.handle_generated_config_bundle.result == 'success'
        uses: actions/cache@v4
        with:
          path: ${{ env.GENERATED_CONFIGS_PATH }}
          key: ${{ env.CACHE_KEY }}-generated-configs
```

We need to investigate whether we can remove this caching step. 
We look into this suggestion: https://github.com/checkstyle/checkstyle/pull/15633#discussion_r1748971809

**Comment by relentless-pursuit** [comment]
**Current scenario:**

1. Cache Saving Step:

In the `handle_generated_config_bundle` job:
```
- name: Cache Generated Config and Project Files
  uses: actions/cache@v4
  with:
    path: ${{ env.GENERATED_CONFIGS_PATH }}
    key: ${{ env.CACHE_KEY }}-generated-configs
```

2. Cache Restoring Step:

In the `download_configs` job:

```
- name: Restore Generated Config and Project Files
  if: needs.handle_generated_config_bundle.result == 'success'
  uses: actions/cache@v4
  with:
    path: ${{ env.GENERATED_CONFIGS_PATH }}
    key: ${{ env.CACHE_KEY }}-generated-configs
```

Proposed solution:
- name: Save cache
  uses: actions/cache/save@v4
  with:
    path: |
      .
      .ci-temp/generated-configs
    key: ${{ env.CACHE_KEY }}
    
And, bypasssing the save cache step. But, it is giving error. 
https://github.com/checkstyle-gsoc/checkstyle/actions/runs/10893791107/job/30229355364

I was thinking why complicate it as generate config is a conditional run. And, if we mix the cache, it adds complexity just to reduce 1 step of cache retrieval. While I am thinking the downsides of it, knowing this specific step is executed only for a specific trigger, and mixing cache might just give us marginal returns as a trade off.
