### ISSUE TITLE
Remove the existing comment option in regression-report.yml getting away with contribution repository

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15675]
Remove:
```
      - name: Comment PR
        uses: checkstyle/contribution/comment-action@master
        with:
          message: ${{steps.out.outputs.message}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Use:
```
      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.out.outputs.message }}
```
