### ISSUE TITLE
migrate to circleci 2.0

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5528]
detected at: 5525

here is how to migrate https://circleci.com/docs/2.0/migrating-from-1-2/ .... 
It would be great if in same time we can move all embedded shell commands to simple commands for shell execution with argument to let us run same commands on local (see how it was done for Travis (travis.sh))

Drawbacks:
 - it will demand new folder in our project. No ways to define a path to config file it has to be ".circleci/config.yml"

Benefits: 
- usage all new features of CI, we do not need any specific, but ...
- one day 1.0 will be deprecated/removed so we will have to upgrade 

> Dear customer, 
We wanted to let you know that we are planning on sunsetting CircleCI 1.0 on August 31st, 2018. Our goal as a company for 2018 is to invest in delivering more features and better performance on CircleCI 2.0, which unlocks faster builds and greater control. For more information, you can read our [blog post](https://circleci.com/blog/sunsetting-1-0) on sunsetting CircleCI 1.0.
You’ll need to update all of your config files to the CircleCI 2.0 syntax in order to migrate your projects to CircleCI 2.0 over the next 6 months.
If all of your projects are already on 2.0, congratulations! No action is necessary. We are sending this announcement to all active users to make sure you have all of the information you need. Take a look at your builds dashboard to see if your projects are still building on CircleCI 1.0: 
These resources will help you get migrate your projects from 1.0 to 2.0:
[Config.yml translator](https://circleci.com/docs/2.0/config-translation). Note: This will generate a baseline config.yml file that you can adjust to fit your needs.
[1.0 to 2.0 migration documentation](https://circleci.com/docs/2.0/migrating-from-1-2/).
[Language-specific 2.0 tutorials](https://circleci.com/docs/2.0/tutorials/).
We will be sending you email reminders periodically with additional resources and links as they become available to help with your migration plan. We will also be updating this page with information relevant to sunsetting CircleCI 1.0. If you need additional migration assistance, open a support request and our support team will be in touch.
Cheers,
The CircleCI Team

**Comment by romani** [comment]
There are two ways:
1) parallelism:
Benefits: single status in PR
Problems: limit to 4, fancy config to make it work, pay attention to `circleci tests split` that rule paralelism
2) workflows 
Benefits: looks like no limits on parallel executions, easy to extend, easy to customize
Problems: produce as much status icons for PR as you have workflows (no general status icon). 


parallelism config:
```
version: 2
jobs:
  build:
    machine: true
    parallelism: 4
    java:
      version: oraclejdk8
    steps:
      - checkout
      - run: git clone https://github.com/checkstyle/contribution
      - restore_cache:
          key: goovy-binaries
      - run: java -version
      #- run: mvn --version
      #- run: if [ ! -d groovy-2.4.7 ]; then wget https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.7.zip && unzip apache-groovy-binary-2.4.7.zip; fi
      - run: pwd
      #- run: java -version
      - run:
          command: |
            echo $(ls -1 .ci/circleci/*.sh | circleci tests split)
            eval $(ls -1 .ci/circleci/*.sh | circleci tests split)
      - save_cache:
          key: goovy-binaries
          paths:
            - groovy-2.4.7
```

Workflow is better approach.
